Merge upstream geth 1.12.0 release
ethereum-optimism/op-geth pull request #104
Opened 2023-06-26 04:52 UTC by ajsutton

**Description**

Pull in changes from upstream geth 1.12.0 release.

2023-07-21 23:41 UTC, protolambda requested changes
The diff looks good, but it looks like all the v1.12.0 were squashed into a single commit, rather than merging the upstream commits as-is? I can't see any double-parent commit or upstream history?

We should checkout the upstream v1.12.0 and create a merge-commit with `optimism`.

2023-07-23 21:38 UTC, ajsutton commented
ah nuts, I see a force push in the history so I'm guessing I lost the merge commit doing whatever I did there... That's going to be a major pain.

2023-07-23 21:54 UTC, ajsutton commented
ok no so bad in the end. Steps to resolve:
1. Checkout this branch, store the current state as a tmp branch and then reset back to `optimism`
2. `git merge v1.12.0` - this results in all the original merge conflicts
3. Used GoLand to diff against original and get all the original changes. That gets the code back to exactly what was in this PR originally but with the upstream geth history.
4. Commit all files except fork.yaml, then commit fork.yaml as a second commit.
5. Confirm that `git diff` reports no changes to either my tmp branch or `origin/aj/1.12.0`

2023-07-24 18:15 UTC, protolambda approved these changes

2023-07-24 18:15 UTC, merged